Update padavan-4.4-build.yml

diff --git a/.github/workflows/padavan-4.4-build.yml b/.github/workflows/padavan-4.4-build.yml
--- a/.github/workflows/padavan-4.4-build.yml
+++ b/.github/workflows/padavan-4.4-build.yml
@@ -1,125 +1,191 @@
-name: padavan-4.4-build
+workflow:
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "web"
+    - if: $CI_PIPELINE_SOURCE == "pipeline"
+    - if: $CI_PIPELINE_SOURCE == "schedule"
 
-on: 
-  workflow_dispatch:
-    inputs:
-      version:
-        description: Test Version
-        default: v1.0.0
-        required: true
+variables:
+  GIT_DEPTH: 1
+  API_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID"
+  TKN: "JOB-TOKEN: $CI_JOB_TOKEN"
+  IMAGE_TAG: latest
+  PACKAGE_NAME: toolchain
+  PACKAGE_VERSION: latest
+  TOOLCHAIN_FILE: toolchain.tzst
 
-jobs:
-  build:
-    name: build
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        target: [NEWIFI-D1, K2P, B70]
-    steps:
-      - uses: actions/checkout@v3
-      - uses: hendrikmuhs/ccache-action@v1.2
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '^1.18.6'
-      - uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-v1
-          restore-keys: |
-            ${{ runner.os }}-go-
-      - name: Prepare
-        run: |
-          sudo apt update
-          sudo apt -y install libtool-bin gperf python3-docutils autopoint gettext ccache
-          # https://github.com/actions/setup-go/issues/107
-          echo "${GOROOT}/bin" >> $GITHUB_PATH
-      - name: Build
-        run: |
-          TNAME=${{ matrix.target }}
-          echo "TNAME=$TNAME"
-          cd trunk
-          if [ ! -f configs/templates/$TNAME.config ] ; then
-          echo "configs/templates/$TNAME.config not found "
-          exit 1
-          fi
-          cp -f configs/templates/$TNAME.config .config
-          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-          ################################################################################################
-          #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
-          ################################################################################################
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
-          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-          sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' .config # 删除fuse
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config # delete OPENVPN
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config # delete HTOP
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config # IPTV
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config # delete OPENSSH
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR/d' .config # delete DropBear SSH
-          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config # shadowsocks
-          ######################################################################
-          #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
-          ######################################################################
-          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
-          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
-          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
-          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config # SS plus+
-          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
-          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
-          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
-          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config #内网穿透FRPC
-          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
-          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
-          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
-          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
-          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
-          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
-          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
-          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
-          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
-          echo "CONFIG_FIRMWARE_ENABLE_FUSE=y" >> .config # fuse
-          echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> .config # openvpn
-          echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config # HTOP
-          echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config # IPTV
-          echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> .config # OPENSSH
-          echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR=y" >> .config # dropbear SSH
-          #########################################################################################
-          #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
-          #格式如下：
-          #sed -i '/自定义项/d' .config
-          #echo "自定义项=y" >> .config
-          #########################################################################################
-          #cp -f .config configs/templates/$TNAME.config
-          cd ..
-          make ${{ matrix.target }}
-          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
-            image=$(ls trunk/images/*.trx)
-            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
-          fi
-          echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
-      - uses: actions/upload-artifact@v3
-        with:
-          name: images
-          path: trunk/images/*.trx
-      - uses: rickstaa/action-create-tag@v1
-        with:
-          tag: ${{ env.TAG_ANME }}
-          force_push_tag: true
-      - uses: ncipollo/release-action@v1
-        with:
-          commit: ${{ github.sha }}
-          tag: ${{ env.TAG_ANME }}
-          artifacts: trunk/images/*.trx
-          allowUpdates: true
+stages:
+  - check
+  - build toolchain
+  - publish package
+  - build image
+
+check:
+  stage: check
+  image: bash
+  rules:
+    - if: $BUILD_TOOLCHAIN == null && $BUILD_CONTAINER == null
+  variables:
+    GIT_STRATEGY: none
+    BUILD_TOOLCHAIN_TRIGGER_PATH: "toolchain"
+    BUILD_CONTAINER_TRIGGER_PATH: "Dockerfile"
+    COMMIT_REF: "$CI_DEFAULT_BRANCH"
+  script:
+    - |
+      apk add --no-cache coreutils curl jq
+
+      echo "Getting container repository ID" # -> "" if no repo
+      container_repo="$(curl -L "$API_URL/registry/repositories" | jq -r '.[0].id | values' ||:)"
+
+      echo "Getting timestamp of the $IMAGE_TAG image" # -> "" if no image
+      image_response="$(curl -L "$API_URL/registry/repositories/$container_repo/tags/$IMAGE_TAG")"
+      image_time="$(jq -r '.created_at | values' <<< "$image_response" ||:)"
+      image_time="$(date +%s -d "${image_time:-0-01-01}")"
+
+      echo "Getting timestamp of the latest commit in $BUILD_CONTAINER_TRIGGER_PATH" # -> "" if no commits
+      commit_response="$(curl -L -G -d "path=$BUILD_CONTAINER_TRIGGER_PATH" \
+                                    -d "ref_name=$COMMIT_REF" "$API_URL/repository/commits")"
+      commit_time="$(jq -r '.[0].committed_date | values' <<< "$commit_response" ||:)"
+      commit_time="$(date +%s -d "${commit_time:-0-01-01}")"
+
+      echo "Will rebuild container image if timestamp $commit_time > $image_time"
+      # new commits to $BUILD_CONTAINER_TRIGGER_PATH since last image build? trigger rebuild
+      if (( commit_time > image_time )); then
+        curl -F "token=$CI_JOB_TOKEN" \
+             -F "variables[BUILD_CONTAINER]=1" \
+             -F "ref=$COMMIT_REF" \
+             "$API_URL/trigger/pipeline"
+      fi
+
+      echo "Getting toolchain package ID" # -> "" if no package
+      package_response="$(curl -LH "$TKN" -G -d "package_type=generic" \
+                                             -d "package_name=$PACKAGE_NAME" "$API_URL/packages")"
+      package_id="$(jq -r '.[] | select(.version == env.PACKAGE_VERSION)
+                               | .id | values' <<< "$package_response" ||:)"
+
+      echo "Getting timestamp of the latest toolchain package" # -> "" if no image
+      files_response="$(curl -LH "$TKN" "$API_URL/packages/$package_id/package_files")"
+      file_time="$(jq -r 'map(select(.file_name == env.TOOLCHAIN_FILE))
+                          | max_by(.id) | .created_at | values' <<< "$files_response" ||:)"
+      file_time="$(date +%s -d "${file_time:-0-01-01}")"
+
+      echo "Getting timestamp of the latest commit in $BUILD_TOOLCHAIN_TRIGGER_PATH" # -> "" if no commits
+      commit_response="$(curl -L -G -d "path=$BUILD_TOOLCHAIN_TRIGGER_PATH" \
+                                    -d "ref_name=$COMMIT_REF" "$API_URL/repository/commits")"
+      commit_time="$(jq -r '.[0].committed_date | values' <<< "$commit_response" ||:)"
+      commit_time="$(date +%s -d "${commit_time:-0-01-01}")"
+
+      echo "Will rebuild toolchain if timestamp $commit_time > $file_time"
+      # new commits to $BUILD_TOOLCHAIN_TRIGGER_PATH since last package build? trigger rebuild
+      if (( commit_time > file_time )); then
+        curl -F "token=$CI_JOB_TOKEN" \
+             -F "variables[BUILD_TOOLCHAIN]=1" \
+             -F "ref=$COMMIT_REF" \
+             "$API_URL/trigger/pipeline"
+      fi
+
+
+build toolchain:
+  stage: build toolchain
+  image: ubuntu:22.04
+  rules:
+    - if: $BUILD_TOOLCHAIN
+  artifacts:
+    expire_in: 1 h
+    paths: [ $TOOLCHAIN_FILE ]
+  script:
+    - |
+      apt update
+      apt install --no-install-recommends -y \
+          autoconf \
+          automake \
+          bison \
+          bzip2 \
+          ca-certificates \
+          flex \
+          g++ \
+          gawk \
+          gcc \
+          git \
+          gperf \
+          help2man \
+          libncurses5-dev \
+          libstdc++6 \
+          libtool \
+          libtool-bin \
+          make \
+          patch \
+          texinfo \
+          unzip \
+          wget \
+          xz-utils \
+          zstd
+
+    - pushd toolchain
+    - ./clean_sources.sh
+    - ./build_toolchain.sh
+    - popd
+
+    - tar -I "zstd -9 -T0" -cf "$TOOLCHAIN_FILE" toolchain/out
+
+
+publish package:
+  stage: publish package
+  image: bash
+  rules:
+    - if: $BUILD_TOOLCHAIN
+  script:
+    - |
+      apk add --no-cache curl jq
+
+      echo "Uploading $TOOLCHAIN_FILE"
+      upload_url="$API_URL/packages/generic/$PACKAGE_NAME/$PACKAGE_VERSION/$TOOLCHAIN_FILE?select=package_file"
+      upload_response="$(curl -LH "$TKN" -T "$TOOLCHAIN_FILE" "$upload_url")"
+      file_id="$(jq -r '.id | values' <<< "$upload_response")"
+      (( file_id > 0 )) || { echo "Upload failed"; exit 1; }
+
+      echo    "Package URL:"
+      echo -n "$CI_API_V4_URL/projects/${CI_PROJECT_NAMESPACE}%2F${CI_PROJECT_NAME}"
+      echo    "/packages/generic/$PACKAGE_NAME/$PACKAGE_VERSION/$TOOLCHAIN_FILE"
+
+      echo "Getting old files list"
+      package_response="$(curl -LH "$TKN" -G -d "package_type=generic" \
+                                             -d "package_name=$PACKAGE_NAME" "$API_URL/packages")"
+      package_id="$(jq -r '.[] | select(.version == env.PACKAGE_VERSION)
+                               | .id | values' <<< "$package_response")"
+
+      files_response="$(curl -LH "$TKN" "$API_URL/packages/$package_id/package_files")"
+      package_files="$(jq -r '.[] | select(.file_name == env.TOOLCHAIN_FILE)
+                                  | .id | values' <<< "$files_response")"
+
+      echo "Removing old files"
+      while IFS= read -r old_file_id; do
+        if [[ -n $old_file_id && $old_file_id != $file_id ]]; then
+          delete_url="$API_URL/packages/$package_id/package_files/$old_file_id"
+          curl -LH "$TKN" -o /dev/null -w "%{http_code}" -X DELETE "$delete_url"
+        fi
+      done <<< "$package_files"
+
+
+build image:
+  stage: build image
+  image: docker:stable
+  services:
+    - docker:dind
+  rules:
+    - if: $BUILD_CONTAINER
+  variables:
+    GIT_STRATEGY: none
+  script:
+    - apk add --no-cache git
+
+    - echo "Sparse checkout"
+    - git clone -n --depth 1 --filter tree:0 "$CI_REPOSITORY_URL"
+    - cd "$CI_PROJECT_NAME"
+    - git sparse-checkout set --no-cone Dockerfile
+    - git checkout
+
+    - echo "Building container image"
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" -f Dockerfile .
+    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
+    - echo "Image is available as $CI_REGISTRY_IMAGE:$IMAGE_TAG"
